services:
  # Phylactery goes here

  redis:
    image: redis:alpine
    networks:
      - backend
    restart: always

  # Postgres
  postgres:
    image: postgres:latest
    networks:
      - backend
    env_file:
      - ./default.env
    volumes:
      - /mnt/persistent/ritual/database/:/var/lib/postgresql/data
    restart: always

  # Lich goes here

  # Phantasm goes here

  # Celery / Something Else goes here


networks:
  proxy:
    external: true
  backend:

secrets:
  django_secret_key:
    file: secrets/django_secret_key.secret
  ucc_email_password:
    file: secrets/ucc_email_password.secret
  postgres_password:
    file: secrets/postgres_password.secret
  discord_bot_token:
    file: secrets/discord_bot_token.secret
