services:
  # Phylactery goes here

  redis:
    image: redis:alpine
    networks:
      - backend
    restart: always

  # Postgres
  postgres:
    image: postgres:latest
    networks:
      - backend
    env_file:
      - ./default.env
    volumes:
      - /mnt/persistent/ritual/database/:/var/lib/postgresql/data
    restart: always

  # Lich goes here

  # Phantasm goes here

  # Celery / Something Else goes here


networks:
  proxy:
    external: true
  backend:

# Secrets go here