services:
  # Phylactery
  phylactery:
    build: ./phylactery_2
    depends_on:
      - redis
      - postgres
    networks:
      - proxy
      - backend
    labels:
      # Traefik:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # Redirect http to https
      - traefik.http.middlewares.phylactery-redirect-websecure.redirectscheme.scheme=https
      - traefik.http.routers.phylactery-web.middlewares=phylactery-redirect-websecure
      - traefik.http.routers.phylactery-web.rule=Host("beta.phylactery.gozz.id.au")
      - traefik.http.routers.phylactery-web.entrypoints=web
      # Accept https with letsencrypt
      - traefik.http.routers.phylactery-websecure.rule=Host("beta.phylactery.gozz.id.au")
      - traefik.http.routers.phylactery-websecure.tls.certresolver=letsencrypt
      - traefik.http.routers.phylactery-websecure.tls=true
      - traefik.http.routers.phylactery-websecure.entrypoints=websecure
      # Port
      - traefik.http.services.phylactery-websecure.loadbalancer.server.port=80
    secrets:
      - django_secret_key
      - ucc_email_password
      - postgres_password
      - discord_oauth_token
    env_file:
      - ./default.env
    volumes:
      - ./settings_override.py:/app/phylactery/settings_override.py
      - /mnt/persistent/ritual/media/:/app/media
    restart: always

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - backend
    volumes:
      - /mnt/persistent/ritual/redis/:/data
    restart: always

  # Postgres
  postgres:
    image: postgres:latest
    networks:
      - backend
    env_file:
      - ./default.env
    secrets:
      - postgres_password
    volumes:
      - /mnt/persistent/ritual/database/:/var/lib/postgresql/data
    restart: always

  # Lich goes here

  # Phantasm goes here

  # Celery / Something Else goes here


networks:
  proxy:
    external: true
  backend:

secrets:
  django_secret_key:
    file: secrets/django_secret_key.secret
  ucc_email_password:
    file: secrets/ucc_email_password.secret
  postgres_password:
    file: secrets/postgres_password.secret
  discord_bot_token:
    file: secrets/discord_bot_token.secret
  discord_oauth_token:
    file: secrets/discord_oauth_token.secret
